# src/Web/MainBundle/Resources/config/routing.yml
main_page:
    pattern:  /
    defaults: { _controller: MainBundle:Site:index }

contact_form:
    pattern:  /site/contact/
    defaults: { _controller: MainBundle:Site:contact }
    requirements:
        _method:  GET|POST

static_page:
    pattern: /site/{page}/
    defaults: { _controller: MainBundle:Site:static }

# Para hacer que la ruta sea valida con slash al final y sin él (ruta y ruta/) se puede utilizar los dos métodos
#    siguientes, uno consiste en utilizar dos rutas, la primera sería sin slash y la segunda con el slash al final y
#    redireccionando a la primera, como se indica abajo. En el otro se utilizaría directamente la ruta con slash
#_static_page:
#    pattern: /site/{page}/
#    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: static_page }

test:
    pattern: /test/
    defaults: { _controller: MainBundle:Site:test }