security:
    firewalls:
        frontend: # Firewall utilizado solo para la parte pública (sólo en el blog)
            pattern: ^/*
            anonymous: ~
            form_login:
                login_path: user_login
                check_path: user_login_check
                use_referer: true
            logout:
                path: user_logout
                #target: /user/adios
            remember_me:
                key: miweb3673
                lifetime: 2592000 # Tiempo en segundos durante el cual será recordado un usuario logueado (1 mes)
        # dev:
        #     pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #     security: false

    providers:
        user:
            entity: { class: UserBundle:User }

    encoders:
        Web\UserBundle\Entity\User: { algorithm: sha512, iterations: 10 }
        # Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        # ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/user/(login|signup), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/activate/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/show/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/*, roles: ROLE_USER }
        # - { path: ^/*, roles: ROLE_USER }
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }