services:
#    user.example:
#        class: %user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    user.register:
        class: Web\UserBundle\Controller\RegisterController
        arguments: [@request_stack, @form.factory]